AWSTemplateFormatVersion: "2010-09-09"
Description: ZoneIngress for the Kuma Counter Demo
Parameters:
  VPCStackName:
    Type: String
    Description: Stack used to create the VPC
  CPStackName:
    Type: String
    Description: Cloudformation stack used to provision the control plane.
  ImageKumaDP:
    Type: String
    Default: "docker.io/bartsmykla/kuma-dp:2.4.3-debug-1"
    Description: Name of the kuma-dp docker image
  DesiredCount:
    Type: String
    Default: 1
    Description: Desired replica count of the workload
  DataplaneSecretPrefix:
    Type: String
    Default: "kong-mesh-ecs"
    Description: Prefix to use for naming dataplane token secrets
  ZoneName:
    Type: String
    Default: "zone"
    Description: Name of the zone

Mappings:
  Config:
    ZoneIngress:
      Port: 10001
      Name: zoneingress
      Template: |
        ---
        type: ZoneIngress
        name: "{{ name }}"
        networking:
          address: "{{ address }}"
          advertisedAddress: "{{ advertisedAddress }}"
          port: "{{ port }}"
          advertisedPort: "{{ advertisedPort }}"

Resources:
  SecretTokenZoneIngress:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Secret containing Kuma Token for ZoneIngress
      Name: !Join ["/", [!Ref DataplaneSecretPrefix, !Ref ZoneName, !FindInMap [Config, ZoneIngress, Name]]]
      SecretString: "{}"

  RoleExecutionTaskZoneIngress:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: [sts:AssumeRole]
      Policies:
        - PolicyName: get-kuma-dp-token-secret
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref SecretTokenZoneIngress
                  - Fn::ImportValue: !Join [":", [!Ref CPStackName, CPCASecret]]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  IamRoleTaskZoneIngress:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs-tasks.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/AWSAppMeshEnvoyAccess
      Tags:
        - Key: kuma.io/type
          Value: ingress
#        - Key: kuma.io/zone
#          Value: !Ref ZoneName

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 7

  SecurityGroupZoneIngress:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ZoneIngress security group
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: tcp
          ToPort: !FindInMap [Config, ZoneIngress, Port]
          FromPort: !FindInMap [Config, ZoneIngress, Port]
        - CidrIp: "0.0.0.0/0"
          IpProtocol: tcp
          ToPort: 9901
          FromPort: 9901
      VpcId:
        Fn::ImportValue: !Join [":", [!Ref VPCStackName, VPCId]]

  LoadBalancerZoneIngress:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      Type: network
      Subnets:
        - Fn::ImportValue: !Join [":", [!Ref VPCStackName, PublicSubnet]]

  LoadBalancerTargetZoneIngress:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      Port: !FindInMap [Config, ZoneIngress, Port]
      Protocol: TCP
      VpcId:
        Fn::ImportValue: !Join [":", [!Ref VPCStackName, VPCId]]
      HealthCheckProtocol: "HTTP"
      HealthCheckPort: "9901"
      HealthCheckPath: "/ready"
      Matcher:
        HttpCode: "200"

  LoadBalancerListenerZoneIngress:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancerZoneIngress
      Port: !FindInMap [Config, ZoneIngress, Port]
      Protocol: TCP
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref LoadBalancerTargetZoneIngress

  ServiceZoneIngress:
    Type: AWS::ECS::Service
    Properties:
      LaunchType: FARGATE
      Cluster:
        Fn::ImportValue: !Join [":", [!Ref VPCStackName, ClusterName]]
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinitionZoneIngress
      PropagateTags: SERVICE
      ServiceName: !Join ["-", [!Ref ZoneName, !FindInMap [Config, ZoneIngress, Name]]]
      LoadBalancers:
        - TargetGroupArn: !Ref LoadBalancerTargetZoneIngress
          ContainerPort: !FindInMap [Config, ZoneIngress, Port]
          ContainerName: zoneingress
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Fn::ImportValue: !Join [":", [!Ref VPCStackName, PublicSubnet]]
          SecurityGroups:
            - !Ref SecurityGroupZoneIngress
            - Fn::ImportValue:
                !Join [":", [!Ref VPCStackName, FargateContainerSecurityGroup]]

  TaskDefinitionZoneIngress:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Join ["-", [!Ref ZoneName, !FindInMap [Config, ZoneIngress, Name]]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !Ref IamRoleTaskZoneIngress
      ExecutionRoleArn: !Ref RoleExecutionTaskZoneIngress
      Cpu: 256
      Memory: 512
      ContainerDefinitions:
        - Name: zoneingress
          Image: !Ref ImageKumaDP
          PortMappings:
            - ContainerPort: !FindInMap [Config, ZoneIngress, Port]
              Protocol: tcp
          Essential: true
          Secrets:
            - Name: KUMA_CONTROL_PLANE_CA_CERT
              ValueFrom:
                Fn::ImportValue: !Join [":", [!Ref CPStackName, CPCASecret]]
          Environment:
            - Name: KUMA_DATAPLANE_RUNTIME_RESOURCE
              Value: !FindInMap [Config, ZoneIngress, Template]
          EntryPoint: ["sh", "-c"]
          Command:
            - !Join
              - " "
              - - kuma-dp
                - run
                - --proxy-type
                - ingress
                - --cp-address
                - Fn::Sub:
                    - https://${Hostname}:5678
                    - Hostname:
                        Fn::ImportValue: !Join [":", [!Ref CPStackName, CPAddress]]
                - --dataplane-var
                - !Join ["=", [name, !Join ["-", [!Ref ZoneName, !FindInMap [Config, ZoneIngress, Name]]]]]
                - --dataplane-var
                - address=`hostname -i`
                - --dataplane-var
                - !Join ["=", [advertisedAddress, !GetAtt LoadBalancerZoneIngress.DNSName]]
                - --dataplane-var
                - !Join ["=", [port, !FindInMap [Config, ZoneIngress, Port]]]
                - --dataplane-var
                - !Join ["=", [advertisedPort, !FindInMap [Config, ZoneIngress, Port]]]
                - --auth-type=aws
          HealthCheck:
            Command:
              [
                CMD, "/busybox/busybox", "sh", "-c",
                "wget -q -O - http://localhost:9901/ready || exit 1",
              ]
            StartPeriod: 5
            Interval: 10
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AWS::StackName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: zoneingress

Outputs:
  LoadBalancerAddress:
    Description: Address of the ZoneIngress load balancer
    Value: !GetAtt LoadBalancerZoneIngress.DNSName
    Export:
      Name: !Join [":", [!Ref AWS::StackName, LoadBalancerAddress]]
